FROM python:3.7-alpine3.9
WORKDIR /usr/src/app
EXPOSE 8000
RUN apk add curl
COPY requirements.txt .
RUN pip install -qr requirements.txt
COPY consul /bin/
ADD entry-point.sh /bin/
COPY envconsul /bin/
COPY server.py .
ENTRYPOINT ["entry-point.sh"]
CMD ["python3", "./server.py"]